import Vue from "vue";
import "vue-awesome/icons/caret-down";
import "vue-awesome/icons/caret-up";
import "vue-awesome/icons/phone";
import "vue-awesome/icons/calendar";
import "vue-awesome/icons/tv";
import "vue-awesome/icons/cog";
import "vue-awesome/icons/clock-o";
import "vue-awesome/icons/pencil";
import "vue-awesome/icons/search";
import "vue-awesome/icons/close";
import "vue-awesome/icons/twitter";
import "vue-awesome/icons/linkedin-square";
import "vue-awesome/icons/dropbox";
import "vue-awesome/icons/clone";
import "vue-awesome/icons/file-text-o";
import "vue-awesome/icons/user-plus";
import "vue-awesome/icons/microphone";
import "vue-awesome/icons/microphone-slash";
import "vue-awesome/icons/lock";
import "vue-awesome/icons/times";
import "vue-awesome/icons/video-camera";
import "vue-awesome/icons/user";
import "vue-awesome/icons/comments";
import "vue-awesome/icons/question-circle";
import "vue-awesome/icons/volume-off";
import "vue-awesome/icons/volume-up";
import "vue-awesome/icons/times-circle";
import "vue-awesome/icons/file-word-o";
import "vue-awesome/icons/desktop";
import "vue-awesome/icons/angle-down";
import "vue-awesome/icons/angle-left";
import "vue-awesome/icons/undo";
import "vue-awesome/icons/play";
import "vue-awesome/icons/map-pin";
import "vue-awesome/icons/share";
import "vue-awesome/icons/arrow-down";
import "vue-awesome/icons/facebook";
import "vue-awesome/icons/google-plus";
import "vue-awesome/icons/backward";
import "vue-awesome/icons/forward";
import "vue-awesome/icons/retweet";
import "vue-awesome/icons/angle-down";
import "vue-awesome/icons/check-circle";

import Icon from "vue-awesome/components/Icon";

Vue.component("icon", Icon);
